# Data processing
RAW_DATA_PATH: 'data'
CLEAN_DATA_PATH: 'data_clean'
STOCK_DATA_PATH: 'stock_data'
ALLOWED_DATASETS: ['gspc', 'hsi', 'ks11', 'sx5e']
INDEX_SYMBOLS: { '^GSPC', '^HSI', '^KOSPI' }
INDEX_SPLITS: {
  "gspc": {
    "train": ["1987-01-02", "2002-11-04"],
    "valid": ["2002-11-05", "2006-08-10"],
    "full_train": ["1987-01-02", "2006-08-10"],
    "test": ["2006-08-11", "2017-12-29"]
  }
}
LOOKBACK: 200

# Model
SHARE_TRADE_LIMIT: 1
STRATEGY:  1
THRESHOLD: 0.2

# Training
EPSILON: 0.1
EPISODES: 30
LR: 0.0001
LR_NUMDREGAD: 0.0000001
LR_NUMDREGID: 0.00001
BATCH_SIZE: 64
GAMMA: 0.85
#TODO: Do we need this and what do we set it to?
MEMORY_CAPACITY: 256
MIN_MEMORY_CAPACITY: 200
EPISODES_PER_TARGET_UPDATE: 1
