# Data processing
RAW_DATA_PATH: 'data'
CLEAN_DATA_PATH: 'data_clean'
ALLOWED_DATASETS: ['gspc', 'hsi', 'ks11', 'sx5e']
LOOKBACK: 200

# Model
SHARE_TRADE_LIMIT: 10
STRATEGY: 0
THRESHOLD: 0.2

# Training
USE_VALID: True
EPISODES: 2
LR: 0.0001
LR_NUMDREGAD: 0.0000001
LR_NUMDREGID: 0.00001
BATCH_SIZE: 64
GAMMA: 0.85
#TODO: Do we need this and what do we set it to?
MEMORY_CAPACITY: 256
MIN_MEMORY_CAPACITY: 200
